mali_kbase: mem_pool: convert to shrinker_register() (v6.7 compatibility)
Linux commit [1] has removed some old shrinker APIs and this causes
this OOT pixel driver to fail compilation:

    .../gpu/mali_kbase/mali_kbase_mem_pool.c:596:2: error: call to undeclared function 'register_shrinker'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            register_shrinker(&pool->reclaim, "mali-mem-pool");
            ^
    .../gpu/mali_kbase/mali_kbase_mem_pool.c:596:2: note: did you mean 'register_chrdev'?
    .../common/include/linux/fs.h:2604:19: note: 'register_chrdev' declared here
    static inline int register_chrdev(unsigned int major, const char *name,
                      ^
    .../gpu/mali_kbase/mali_kbase_mem_pool.c:623:2: error: call to undeclared function 'unregister_shrinker'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
            unregister_shrinker(&pool->reclaim);
            ^
    .../gpu/mali_kbase/mali_kbase_mem_pool.c:623:2: note: did you mean 'unregister_chrdev'?
    .../include/linux/fs.h:2610:20: note: 'unregister_chrdev' declared here
    static inline void unregister_chrdev(unsigned int major, const char *name)
                       ^
    2 errors generated.

Update the driver accordingly.

Note that it's needlessly hard to keep the #ifdef'ery for older
kernels, so we just drop them at this stage.

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=f2383e01507e
    ("mm: shrinker: remove old APIs")

Bug: 316904748
Test: TH
Change-Id: I2494419ca0c4542ce8866207f1070e43f3b9c67e
Signed-off-by: André Draszik <draszik@google.com>
(cherry picked from commit b44eeb569450fa592a9000ca4a5351a02b36cab6)