mali_kbase: FMODE_UNSIGNED_OFFSET has moved to fop_flags (v6.12 compat)
Linux commit [1] has moved FMODE_UNSIGNED_OFFSET from struct
file::f_mode to struct file_operations::fop_flags.

This causes compilation of this driver to fail:
.../mali_kbase/mali_kbase_core_linux.c:800:18:
error: use of undeclared identifier 'FMODE_UNSIGNED_OFFSET'
  800 |         filp->f_mode |= FMODE_UNSIGNED_OFFSET;
      |                         ^

Update the code similar to the upstream changes.

Link: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=641bb4394f40 [1]
      ("fs: move FMODE_UNSIGNED_OFFSET to fop_flags")
Test: TH
Bug: 369257612
Change-Id: Ib3ff8aef2529370125bf1101da56595e535b947e
Signed-off-by: André Draszik <draszik@google.com>
Signed-off-by: Will McVicker <willmcvicker@google.com>