mali_kbase_debug_mem_view: get_file_rcu() update for v6.7 kernel
Linux commit [1] has updated get_file_rcu() and this causes this
OOT pixel driver to fail compilation:

    .../gpu/mali_kbase/mali_kbase_debug_mem_view.c:237:19: error: incompatible pointer types passing 'struct file *' to parameter of type 'struct file  btf_type_tag(rcu)**' (aka 'struct file **'); take the address with & [-Werror,-Wincompatible-pointer-types]
            if (get_file_rcu(kctx->filp) == 0)
                             ^~~~~~~~~~
                             &
    .../common/include/linux/fs.h:1046:47: note: passing argument to parameter 'f' here
    struct file *get_file_rcu(struct file __rcu **f);
                                                  ^
    1 error generated.

Note that upstream has fixed this in a completely different way as part of a code-drop:
    dacf004cc8a4 mini release: update r44p1-01bet1 to r44p1-00dev2
    127 files changed, 6818 insertions(+), 3156 deletions(-)
which we received as part of pa/2579253

For now, just go with this simple version to make it compile and
somewhat work (this here is only used for debugfs access).

[1] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0ede61d8589c
    ("file: convert to SLAB_TYPESAFE_BY_RCU")

Test: find /sys/kernel/debug/mali* -name mem_view -exec sh -c 'echo "${1}" ; head "${1}"' _ {} \;
Change-Id: I753629270ada2141fb7c863631a90d784b47cff9
Signed-off-by: André Draszik <draszik@google.com>